### ISSUE TITLE
Set up Eslint

### ISSUE THREAD

**Issue by kholoudfann** [GSG-K3/code-academy-wiki#37]

**Comment by bayan-404** [comment]
## Linting
-  Using eslint with the Airbnb style guide configuration


## React Installing
To install the package and its dependencies:

```shell
$ npm install --save-dev eslint@4.19.1 \
                         eslint-config-pagarme-react \
                         stylelint@8.0.0 \
                         stylelint-config-pagarme-react \
```

> The peer dependencies specified above have hardcoded versions.
> If you prefer, you can use the command
> `npm info eslint-config-pagarme-react@latest peerDependencies`
> to find the exact peer dependencies to install.

To include these rules into your project, create the following config files in your root folder:

> `.eslintrc`

```json
{
  "extends": ["pagarme-react"],
  "env": {
    "browser": true
  }
}
```

> `.stylelintrc`
```
{
  "extends": ["stylelint-config-pagarme-react"]
}

**Comment by kholoudfann** [comment]
done
