### ISSUE TITLE
Create Navbar

### ISSUE THREAD

**Issue by Rahaf-96** [GSG-K3/code-academy-wiki#40]

**Comment by bayan-404** [comment]
this issue is related to issue #30

**Comment by bayan-404** [comment]
- [ ] creating the navbar section with css :octocat::sparkles:

![Selection_031](https://user-images.githubusercontent.com/57558867/80291551-215f0000-8757-11ea-9c8b-dfc29dbc0806.png)

**Comment by bayan-404** [comment]
- [ ] creating the cohorts Drop down list  :small_red_triangle_down:

![Group 3717](https://user-images.githubusercontent.com/57558867/80291743-ebbb1680-8758-11ea-81ef-ec7cd14b7bd2.png)
